### ISSUE TITLE
"Videos/Wiedergabelisten übertragen" is not working

### ISSUE THREAD

**Issue by kai-wng-uos** [elan-ev/studip-opencast-plugin#879] opened 2024-01-10 10:40 UTC
Several issues with this feature:

-  the way the button is worded, it suggests that you can choose specific videos and/or playlists to transfer between courses. The dialog then suggests all contents of the course are being transferred. I would suggest changing the button to "Kursinhalte übertragen"
- when you then try to transfer all contents (as the dialog claims) to a different course, all playlists and the videos in those playlists are transferred to the chosen course. However, the videos from the "Kurswiedergabeliste" are not transferred. 
- Instead of the videos from the start course's "Kurswiedergabeliste" being transferred to the destination course's "Kurswiedergabeliste", videos from the other transferred playlists are listed there. 
- I have not yet figured out why certain videos from the playlists are shown in the "Kurswiedergabeliste" but other are not

**Comment by kai-wng-uos** [comment] 2024-01-10 12:45
additionally to this, the playlists are laso not copied to the destination course, but linked, meaning that every change to the playlist in one course will effect this playlist in all courses it has been transferred to. This relates to #797

**Comment by kai-wng-uos** [comment] 2024-01-10 14:18
Also, there are always two videos being added to the course playlist of the destination course. These videos were not part of any playlists in the original course, yet they crop up in the course playlist.

**Comment by kai-wng-uos** [comment] 2024-01-15 10:47
Further testing shows that the migration between courses seems to be working with all playlists except the course playlist. Here, the migration is very inconsistent. Sometimes it works fine, sometimes only certain videos are transferred, sometimes none. @tgloeggl could this be a test system issue?

**Comment by dennis531** [comment] 2024-01-22 16:55
I think most of the problems could be solved by https://github.com/elan-ev/studip-opencast-plugin/pull/893. Now the "Videos/Wiedergabelisten übertragen" action copies all playlists including the "Kurswiedergabeliste" playlist to the destination course.

**Comment by dennis531** [comment] 2024-01-23 09:54
> when you then try to transfer all contents (as the dialog claims) to a different course, all playlists and the videos in those playlists are transferred to the chosen course. However, the videos from the "Kurswiedergabeliste" are not transferred.

Should be solved by #893.

> Instead of the videos from the start course's "Kurswiedergabeliste" being transferred to the destination course's "Kurswiedergabeliste", videos from the other transferred playlists are listed there.

Probably caused by https://github.com/elan-ev/studip-opencast-plugin/issues/901. Shoud be solved by https://github.com/elan-ev/studip-opencast-plugin/pull/906.

> I have not yet figured out why certain videos from the playlists are shown in the "Kurswiedergabeliste" but other are not

This problem could be related to #901 or is/was caused by false or confusing video permissions.

> additionally to this, the playlists are laso not copied to the destination course, but linked, meaning that every change to the playlist in one course will effect this playlist in all courses it has been transferred to. This relates to https://github.com/elan-ev/studip-opencast-plugin/issues/797. On the other hand, deleting a playlist from a course (no matter if it's the start or destination course) doesn't affect the playlists in transferred courses --> inconsistent.

I hope it is solved by #893

**Comment by dennis531** [comment] 2024-01-23 10:42
After https://github.com/elan-ev/studip-opencast-plugin/pull/906 is merged, this function should be tested again.

**Comment by kai-wng-uos** [comment] 2024-01-31 09:01
currently not working at all...

https://github.com/elan-ev/studip-opencast-plugin/assets/152959695/7fabc66d-863a-4e9c-bfa5-3ad5413105e2

**Comment by kai-wng-uos** [comment] 2024-01-31 10:26
turns out it is working, but the transferred data only appears after you've (manually) created a playlist. Very confusing. Either add a warning that says something like "um Inhalte in diesen Kurs zu übertragen, müssen Sie zunächst eine Standardplaylist in dem Kurs anlegen", or just make the origin course's default playlist the default playlist for the destination course.

**Comment by dennis531** [comment] 2024-01-31 13:51
Possible solution:
- If no default playlist is set in target course, set default playlist of source course as default
- Otherwise don't change default course

Should match the second solution in https://github.com/elan-ev/studip-opencast-plugin/issues/879#issuecomment-1918817854.

**Comment by kai-wng-uos** [comment] 2024-02-12 14:53
The initial Problem is solved, however, it still has a few problems:
- To perform the transfer, the OC Plugin has to already be activated. The more elegant solution would be that the transfer automatically activates the plugin in the target course
- the playlists are displayed in a different order than in the source course

**Comment by dennis531** [comment] 2024-02-13 14:56
> * To perform the transfer, the OC Plugin has to already be activated. The more elegant solution would be that the transfer automatically activates the plugin in the target course

I am rather against automatically activating the plugin. I think the user should have control over the activation of the plugin in the course. By activating the plugin manually, lecturers can keep better track of which courses are activated, instead of enabling it magically in the background. In addition, we would need to provide some kind of notification when the plugin is activated in the background. 

> the playlists are displayed in a different order than in the source course

I will fix this problem.

**Comment by dennis531** [comment] 2024-02-14 08:14
Playlists in the course are currently sorted in ascending order by their creation date. The problem occurs because the copied playlists do not copy the creation date, but set the copy date as creation date instead. I tried to copy the playlists sorted by creation date. This approach does not work, as all copied playlists ended with the same creation dates, at least in my test system. So this problem is not trivial to solve as long as we do not offer a sorting option for the playlists in the course. It would be possible to offset the mkdates, e.g. by one second. But that would lead to messy hacks in the code.

**Comment by kai-wng-uos** [comment] 2024-02-14 08:23
> > * To perform the transfer, the OC Plugin has to already be activated. The more elegant solution would be that the transfer automatically activates the plugin in the target course
> 
> I am rather against automatically activating the plugin. I think the user should have control over the activation of the plugin in the course. By activating the plugin manually, lecturers can keep better track of which courses are activated, instead of enabling it magically in the background. In addition, we would need to provide some kind of notification when the plugin is activated in the background.

I understand the approach to make actions as transparent as possible. However, I also think in attempting to copy Opencast contents from one course to the next it is clear that a lecturer wants to also activate the plugin, so why make them leave the copying dialog, go to the target course manually, activate the pluging, then return to the original course and start the copying action. To me, this seems unnecessarily tedious. Maybe a notification as to the automatic activation would be a good middle ground?

**Comment by dennis531** [comment] 2024-02-21 15:08
I created new issues for the mentioned problems.

**Closed by dennis531** 2024-02-21 15:08 UTC
Labels: v:3
